### ISSUE TITLE
java.lang.NullPointerException while execution mvn clean install on demo-project

### ISSUE THREAD

**Issue by bpauli** [wmono/jtsc#1]
While executing mvn clean install on the demo-project I got a NPE

trace
```
[ERROR] Failed to execute goal ca.eqv.jtsc:jtsc-maven-plugin:0.1.0.BUILD-SNAPSHOT:compile (default) on project demo-project: Unable to load TypeScript compiler: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal ca.eqv.jtsc:jtsc-maven-plugin:0.1.0.BUILD-SNAPSHOT:compile (default) on project demo-project: Unable to load TypeScript compiler
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to load TypeScript compiler
	at ca.eqv.jtsc.mojo.CompileMojo.compile(CompileMojo.java:53)
	at ca.eqv.jtsc.mojo.CompileMojo.execute(CompileMojo.java:37)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at jdk.nashorn.internal.codegen.MethodEmitter.pushType(MethodEmitter.java:221)
	at jdk.nashorn.internal.codegen.MethodEmitter.load(MethodEmitter.java:821)
	at jdk.nashorn.internal.codegen.MethodEmitter.loadCompilerConstant(MethodEmitter.java:905)
	at jdk.nashorn.internal.codegen.CodeGenerator.enterSplitNode(CodeGenerator.java:1784)
	at jdk.nashorn.internal.ir.SplitNode.accept(SplitNode.java:84)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.LexicalContextStatement.accept(LexicalContextStatement.java:53)
	at jdk.nashorn.internal.ir.SplitNode.accept(SplitNode.java:35)
	at jdk.nashorn.internal.ir.Node.accept(Node.java:291)
	at jdk.nashorn.internal.ir.Block.accept(Block.java:143)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.Block.accept(Block.java:361)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:309)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:46)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:50)
	at jdk.nashorn.internal.codegen.CodeGenerator$1.enterFunctionNode(CodeGenerator.java:456)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:308)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:46)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:50)
	at jdk.nashorn.internal.codegen.CodeGenerator.load(CodeGenerator.java:424)
	at jdk.nashorn.internal.codegen.CodeGenerator.load(CodeGenerator.java:403)
	at jdk.nashorn.internal.codegen.CodeGenerator.enterVarNode(CodeGenerator.java:2183)
	at jdk.nashorn.internal.ir.VarNode.accept(VarNode.java:125)
	at jdk.nashorn.internal.ir.Node.accept(Node.java:291)
	at jdk.nashorn.internal.ir.Block.accept(Block.java:143)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.Block.accept(Block.java:361)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:309)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:46)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:50)
	at jdk.nashorn.internal.codegen.CodeGenerator$2.enterFunctionNode(CodeGenerator.java:780)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:308)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:46)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:50)
	at jdk.nashorn.internal.codegen.CodeGenerator.enterCallNode(CodeGenerator.java:667)
	at jdk.nashorn.internal.codegen.CodeGenerator.access$200(CodeGenerator.java:154)
	at jdk.nashorn.internal.codegen.CodeGenerator$1.enterCallNode(CodeGenerator.java:468)
	at jdk.nashorn.internal.ir.CallNode.accept(CallNode.java:186)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:46)
	at jdk.nashorn.internal.ir.CallNode.accept(CallNode.java:38)
	at jdk.nashorn.internal.codegen.CodeGenerator.load(CodeGenerator.java:424)
	at jdk.nashorn.internal.codegen.CodeGenerator.load(CodeGenerator.java:403)
	at jdk.nashorn.internal.codegen.CodeGenerator$8.evaluate(CodeGenerator.java:2474)
	at jdk.nashorn.internal.codegen.CodeGenerator$Store.store(CodeGenerator.java:3209)
	at jdk.nashorn.internal.codegen.CodeGenerator.enterASSIGN(CodeGenerator.java:2479)
	at jdk.nashorn.internal.ir.visitor.NodeOperatorVisitor.enterBinaryNode(NodeOperatorVisitor.java:117)
	at jdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:168)
	at jdk.nashorn.internal.codegen.CodeGenerator$1.enterDefault(CodeGenerator.java:479)
	at jdk.nashorn.internal.ir.visitor.NodeVisitor.enterBinaryNode(NodeVisitor.java:178)
	at jdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:168)
	at jdk.nashorn.internal.codegen.CodeGenerator.load(CodeGenerator.java:424)
	at jdk.nashorn.internal.codegen.CodeGenerator.load(CodeGenerator.java:359)
	at jdk.nashorn.internal.codegen.CodeGenerator.enterDISCARD(CodeGenerator.java:2348)
	at jdk.nashorn.internal.ir.visitor.NodeOperatorVisitor.enterUnaryNode(NodeOperatorVisitor.java:57)
	at jdk.nashorn.internal.ir.UnaryNode.accept(UnaryNode.java:124)
	at jdk.nashorn.internal.codegen.CodeGenerator.enterExpressionStatement(CodeGenerator.java:857)
	at jdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:66)
	at jdk.nashorn.internal.ir.Node.accept(Node.java:291)
	at jdk.nashorn.internal.ir.Block.accept(Block.java:143)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.Block.accept(Block.java:361)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:309)
	at jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
	at jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:46)
	at jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:50)
	at jdk.nashorn.internal.codegen.CompilationPhase$8.transform(CompilationPhase.java:379)
	at jdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:513)
	at jdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:361)
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1071)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1019)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:490)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:651)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:640)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:521)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:192)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at ca.eqv.jtsc.Compiler.loadTsLib(Compiler.java:64)
	at ca.eqv.jtsc.Compiler.<init>(Compiler.java:28)
	at ca.eqv.jtsc.mojo.CompileMojo.compile(CompileMojo.java:50)
	... 23 more
```

env
```
mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

**Comment by bpauli** [comment]
Issue does not exist anymore with Java version: 1.8.0_112 

Might be related to https://bugs.openjdk.java.net/browse/JDK-8074545
